name: TF Terrascan - security analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          verbose: true
